language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic
    # Adding jobs for ppc64le
    - php: 5.6
      arch: ppc64le
      dist: xenial
    - php: 7.0
      arch: ppc64le
      dist: xenial
    - php: 7.1
      arch: ppc64le
      dist: bionic
    - php: 7.2
      arch: ppc64le
      dist: bionic
    - php: 7.4
      arch: ppc64le
      dist: bionic
    - php: nightly
      arch: ppc64le
      dist: bionic

  fast_finish: true

install:
  - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then travis_retry composer update; fi
  - if [ "$TRAVIS_PHP_VERSION" == "nightly" ]; then travis_retry composer update --ignore-platform-reqs; fi

script: vendor/bin/phpunit
